/**
 * Build a single HTML+JS snippet for Wild Apricot Custom HTML gadgets.
 *
 * Usage:
 *   APPS_SCRIPT_URL='https://script.google.com/...' WA_SITE_URL='https://www.aiwcduesseldorf.org' npm run build:widget
 *
 * Output: dist/aiwcd-step-counter-widget.html  (paste entire file into WA)
 * Limit: Wild Apricot Custom HTML max ~2,048,000 characters
 */
import * as esbuild from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MAX_CHARS = 2_048_000;

const appsScriptUrl = process.env.APPS_SCRIPT_URL || 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL';
const waSiteUrl = process.env.WA_SITE_URL || 'https://www.aiwcduesseldorf.org';

const config = {
  MODE: 'prod',
  EMBEDDED: true,
  APPS_SCRIPT_URL: appsScriptUrl,
  WA_SITE_URL: waSiteUrl,
  AUTH_START_PATH: '?action=auth_start',
};

const outdir = path.join(ROOT, 'dist');
await fs.mkdir(outdir, { recursive: true });

const bundle = await esbuild.build({
  entryPoints: [path.join(ROOT, 'src/app.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2018'],
  write: false,
  minify: true,
  legalComments: 'none',
});

const js = bundle.outputFiles[0].text;
let css = await fs.readFile(path.join(ROOT, 'styles.css'), 'utf8');
// Widget is embedded — drop standalone body background rule
css = css.replace(/^body\s*\{[^}]*\}\s*/m, '');

const indexHtml = await fs.readFile(path.join(ROOT, 'index.html'), 'utf8');
const markupMatch = indexHtml.match(
  /<!-- WIDGET_MARKUP_START -->\s*([\s\S]*?)\s*<!-- WIDGET_MARKUP_END -->/,
);
if (!markupMatch) {
  throw new Error('Could not find WIDGET_MARKUP_START/END markers in index.html');
}
const markup = markupMatch[1].trim();

const snippet = `<!-- AIWCD Step Counter widget — generated by npm run build:widget -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Raleway:wght@600;700&display=swap" rel="stylesheet" />
<style>
${css}
</style>
${markup}
<script>
window.STEP_COUNTER_CONFIG = ${JSON.stringify(config, null, 2)};
${js}
</script>
`;

const outFile = path.join(outdir, 'aiwcd-step-counter-widget.html');
await fs.writeFile(outFile, snippet, 'utf8');

const chars = snippet.length;
console.log(`Wrote ${outFile}`);
console.log(`Characters: ${chars.toLocaleString()} / ${MAX_CHARS.toLocaleString()} (${((chars / MAX_CHARS) * 100).toFixed(2)}% of WA limit)`);
if (chars > MAX_CHARS) {
  console.error('ERROR: exceeds Wild Apricot Custom HTML character limit');
  process.exit(1);
}
if (appsScriptUrl.includes('REPLACE_WITH')) {
  console.log('NOTE: Set APPS_SCRIPT_URL when building for production paste.');
}
