/**
 * Build one production Wild Apricot Custom HTML gadget with all three surfaces:
 * club total + leaderboard + Walkathon track.
 *
 * Always production: no local mock API, no mock sign-in UI.
 * One paste → one script → no multi-gadget races on a WA page.
 *
 * Usage:
 *   APPS_SCRIPT_URL='https://script.google.com/...' WA_SITE_URL='https://www.aiwcduesseldorf.org' npm run build:widget
 *
 * Output:
 *   dist/aiwcd-steps-widget.html
 *
 * Limit: Wild Apricot Custom HTML max ~2,048,000 characters per gadget
 */
import * as esbuild from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MAX_CHARS = 2_048_000;

const appsScriptUrl = process.env.APPS_SCRIPT_URL || 'REPLACE_WITH_APPS_SCRIPT_WEB_APP_URL';
const waSiteUrl = process.env.WA_SITE_URL || 'https://www.aiwcduesseldorf.org';
const joinUrl = process.env.JOIN_URL || '';
/** Hosted interactive app (GitHub Pages). Required — WA CSP blocks Apps Script from the embed. */
const appUrl = process.env.APP_URL || '';

const outdir = path.join(ROOT, 'dist');
await fs.mkdir(outdir, { recursive: true });

const apiJs = path.join(ROOT, 'src/api.js');
const apiWidgetJs = path.join(ROOT, 'src/api.widget.js');

const bundle = await esbuild.build({
  entryPoints: [path.join(ROOT, 'src/app.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2018'],
  write: false,
  minify: true,
  legalComments: 'none',
  plugins: [
    {
      name: 'widget-prod-api',
      setup(build) {
        build.onResolve({ filter: /(?:^|\/)api\.js$/ }, (args) => {
          const resolved = path.resolve(args.resolveDir, args.path);
          if (resolved === apiJs) {
            return { path: apiWidgetJs };
          }
        });
      },
    },
  ],
});

const js = bundle.outputFiles[0].text;
if (js.includes('step-counter-local-session') || js.includes('Local API unavailable')) {
  console.error('ERROR: widget bundle still contains local mock API code');
  process.exit(1);
}

let css = await fs.readFile(path.join(ROOT, 'styles.css'), 'utf8');
css = css.replace(/^body\s*\{[^}]*\}\s*/m, '');

const indexHtml = await fs.readFile(path.join(ROOT, 'index.html'), 'utf8');
const markupMatch = indexHtml.match(
  /<!-- WIDGET_MARKUP_START -->\s*([\s\S]*?)\s*<!-- WIDGET_MARKUP_END -->/,
);
if (!markupMatch) {
  throw new Error('Could not find WIDGET_MARKUP_START/END markers in index.html');
}

/** Strip local-dev-only chrome; keep all three sections visible. */
function prepareMarkup(baseMarkup) {
  let markup = baseMarkup.trim();
  markup = markup
    .replace(/<span id="mode-badge"[\s\S]*?<\/span>\s*/i, '')
    .replace(/<div id="mock-users"[\s\S]*?<\/div>\s*/i, '')
    .replace(/<div id="mock-users-board"[\s\S]*?<\/div>\s*/i, '');

  const rootId = 'aiwcd-step-counter';
  markup = markup.replace(
    /id="aiwcd-step-counter"/,
    `id="${rootId}" data-aiwcd-part="all"`,
  );

  // Show every section immediately (no JS-dependent unhide).
  for (const section of ['section-total', 'section-track', 'section-leaderboard']) {
    markup = markup.replace(
      new RegExp(`(<section id="${section}"[^>]*)\\s+hidden`, 'i'),
      '$1',
    );
  }

  // Prod CTAs visible without waiting for JS.
  markup = markup
    .replace(/(<p id="board-gate-action"[^>]*)\s+hidden/i, '$1')
    .replace(/(<p id="track-cta-action"[^>]*)\s+hidden/i, '$1');

  // ASCII-only copy — WA pages often mis-decode curly apostrophes.
  markup = markup
    .replace(/\u2019/g, "'")
    .replace(/\u2018/g, "'")
    .replace(/\u201C/g, '"')
    .replace(/\u201D/g, '"');

  return { markup, rootId };
}

const config = {
  MODE: 'prod',
  EMBEDDED: true,
  PART: 'all',
  APPS_SCRIPT_URL: appsScriptUrl,
  WA_SITE_URL: waSiteUrl,
  JOIN_URL: joinUrl,
  APP_URL: appUrl,
  AUTH_START_PATH: '?action=auth_start',
};

const { markup, rootId } = prepareMarkup(markupMatch[1]);

const snippet = `<!-- AIWCD Steps widget — generated by npm run build:widget -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Raleway:wght@600;700&display=swap" rel="stylesheet" />
<style>
${css}
</style>
${markup}
<script>
(function (boot) {
  window.__AIWCD_BOOT__ = boot;
${js}
})(${JSON.stringify({ rootId, part: 'all', config }, null, 2)});
</script>
`;

const outFile = path.join(outdir, 'aiwcd-steps-widget.html');
await fs.writeFile(outFile, snippet, 'utf8');

const chars = snippet.length;
console.log(`Wrote ${outFile}`);
console.log(
  `  Characters: ${chars.toLocaleString()} / ${MAX_CHARS.toLocaleString()} (${((chars / MAX_CHARS) * 100).toFixed(2)}% of WA limit)`,
);

if (chars > MAX_CHARS) {
  console.error('ERROR: widget exceeds Wild Apricot Custom HTML character limit');
  process.exit(1);
}
if (!/id="section-total"/i.test(markup) || !/id="section-track"/i.test(markup) || !/id="section-leaderboard"/i.test(markup)) {
  console.error('ERROR: combined widget missing one or more sections');
  process.exit(1);
}
if (/\shidden/.test(markup.match(/<section id="section-total"[^>]*>/i)?.[0] || '')) {
  console.error('ERROR: section-total still has hidden attribute');
  process.exit(1);
}

// Remove legacy split builds so old pastes aren't confused with the new artifact.
for (const legacy of [
  'aiwcd-steps-total-widget.html',
  'aiwcd-steps-leaderboard-widget.html',
  'aiwcd-steps-track-widget.html',
  'aiwcd-step-counter-widget.html',
]) {
  try {
    await fs.unlink(path.join(outdir, legacy));
  } catch {
    /* ignore */
  }
}

if (appsScriptUrl.includes('REPLACE_WITH')) {
  console.log('NOTE: Set APPS_SCRIPT_URL when building for production paste.');
}
if (!appUrl) {
  console.log(
    'NOTE: Set APP_URL to your GitHub Pages tracker (e.g. https://user.github.io/step-counter/).',
  );
  console.log('      The WA embed only links there — it cannot call Apps Script (site CSP).');
}
